# Generated by Django 5.2.6 on 2025-10-08 01:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(help_text='RUT del proveedor', max_length=15, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, help_text='Nombre del contacto principal', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntradaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrada', models.CharField(help_text='Número de factura o documento', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('DONACION', 'Donación'), ('AJUSTE', 'Ajuste de Inventario'), ('DEVOLUCION', 'Devolución')], default='COMPRA', max_length=20)),
                ('fecha_compra', models.DateField(help_text='Fecha de la compra/factura')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro en el sistema')),
                ('comprobante', models.ImageField(blank=True, help_text='Foto de la boleta/factura', null=True, upload_to='comprobantes/')),
                ('total_compra', models.DecimalField(blank=True, decimal_places=2, help_text='Total de la compra (opcional)', max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_registradas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'Entrada de Stock',
                'verbose_name_plural': 'Entradas de Stock',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntradaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario de compra', max_digits=10, null=True)),
                ('area_destino', models.ForeignKey(help_text='Área donde se almacena', on_delete=django.db.models.deletion.PROTECT, to='inventario.area')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.entradastock')),
            ],
            options={
                'verbose_name': 'Detalle de Entrada',
                'verbose_name_plural': 'Detalles de Entrada',
            },
        ),
    ]
