# Generated by Django 5.2.6 on 2025-10-23 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_proveedor_entradastock_detalleentradastock'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='detalle_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.detalleentradastock'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.entradastock'),
        ),
        migrations.AlterField(
            model_name='entradastock',
            name='numero_entrada',
            field=models.CharField(blank=True, help_text='Número de factura/boleta (opcional)', max_length=50),
        ),
    ]
