# Generated by Django 5.2.7 on 2025-10-05 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE_AYB', 'Jefe de Alimentos y Bebidas'), ('HOUSEKEEPING', 'Housekeeping'), ('GARZON', 'Garzón/Restaurante'), ('BODEGUERO', 'Bodeguero'), ('GERENCIA', 'Gerencia')], max_length=20)),
                ('area_acceso', models.CharField(choices=[('TODAS', 'Todas las Áreas'), ('BODEGA', 'Solo Bodega'), ('COCINA', 'Solo Cocina'), ('HABITACIONES', 'Solo Habitaciones'), ('BAR', 'Solo Bar'), ('LIMPIEZA', 'Solo Limpieza')], default='TODAS', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('puede_crear_pedidos', models.BooleanField(default=False)),
                ('puede_recibir_pedidos', models.BooleanField(default=False)),
                ('puede_ajustar_inventario', models.BooleanField(default=False)),
                ('puede_ver_reportes', models.BooleanField(default=False)),
                ('puede_administrar_productos', models.BooleanField(default=False)),
                ('puede_administrar_usuarios', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
