# Generated by Django 5.2.7 on 2025-10-05 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('template_nombre', models.CharField(help_text='Nombre del template para generar el reporte', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=15)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('emails_destino', models.TextField(help_text='Emails separados por comas')),
                ('activo', models.BooleanField(default=True)),
                ('proximo_envio', models.DateTimeField(blank=True, null=True)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('areas_default', models.ManyToManyField(blank=True, to='inventario.area')),
                ('categorias_default', models.ManyToManyField(blank=True, to='inventario.categoria')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_reporte', to=settings.AUTH_USER_MODEL)),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='reportes.tiporeporte')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error en Generación')], default='GENERADO', max_length=15)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tamaño_archivo', models.IntegerField(blank=True, help_text='Tamaño en bytes', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('areas', models.ManyToManyField(blank=True, help_text='Filtrar por áreas', to='inventario.area')),
                ('categorias', models.ManyToManyField(blank=True, help_text='Filtrar por categorías', to='inventario.categoria')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(blank=True, help_text='Filtrar por productos específicos', to='inventario.producto')),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='reportes.tiporeporte')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='LogReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('GENERADO', 'Reporte Generado'), ('ENVIADO', 'Reporte Enviado'), ('ERROR_GENERACION', 'Error en Generación'), ('ERROR_ENVIO', 'Error en Envío')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('configuracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reportes.configuracionreporte')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reportes.reporte')),
            ],
            options={
                'verbose_name': 'Log de Reporte',
                'verbose_name_plural': 'Logs de Reporte',
                'ordering': ['-fecha'],
            },
        ),
    ]
