# Generated by Django 5.2.6 on 2025-11-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_backlogitem_kanbancard_sprintplanitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbancard',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='sprintplanitem',
            name='creado_por',
        ),
        migrations.DeleteModel(
            name='BacklogItem',
        ),
        migrations.DeleteModel(
            name='KanbanCard',
        ),
        migrations.DeleteModel(
            name='SprintPlanItem',
        ),
    ]
